### ISSUE TITLE
Pick appropriate journal

### ISSUE THREAD

**Issue by vbassn** [dtcc-platform/dtcc#28]
E.g 

CEUS 
https://www.sciencedirect.com/journal/computers-environment-and-urban-systems

ISPRS 
https://www.sciencedirect.com/journal/isprs-journal-of-photogrammetry-and-remote-sensing

IEEE https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=36
Transactions on Geoscience and Remote Sensing

Impact Factors

6.4    CEUS
8.2    IEEE
11.7  ISPRS

**Comment by anestiskaim11** [comment]
https://www.sciencedirect.com/journal/remote-sensing-of-environment 
Impact Factor 14

**Comment by anestiskaim11** [comment]
https://www.tandfonline.com/journals/tgrs20
Impact Factor 6.4

**Comment by anestiskaim11** [comment]
List with Remote Sensing journals and ranking: https://ooir.org/journals.php?field=Engineering&category=Remote+Sensing&metric=jif
