### ISSUE TITLE
API: Expose LODs

### ISSUE THREAD

**Issue by anderslogg** [dtcc-platform/dtcc#71]
Suggest renaming ``GeometryType`` --> ``LOD`` and exposing in interface. Now requires extra import

    from dtcc_model.object.object import GeometryType

Want to be able to do both of these:

    geometry = object.geometry[LOD2]
    geometry = object.geometry.LOD2

**Comment by dwastberg** [comment]
GeometryType includes things other than just LOD, like Raster, Pointclouds etc. Perhaps make LOD a separate thing from GeometryType since conceptually you can have a VolumeMesh geometry type with LoD1 and LoD2

**Comment by dwastberg** [comment]
Merged with [this issue](https://github.com/orgs/dtcc-platform/projects/3/views/1?pane=issue&itemId=90815408&issue=dtcc-platform%7Cdtcc-core%7C5)
